memory_limit = 512M
upload_max_filesize = 32M
post_max_size = 32M
max_execution_time = 60
date.timezone = Atlantic/Madeira

opcache.enable = 1
opcache.enable_cli = 0
opcache.jit = tracing
opcache.jit_buffer_size = 64M
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
